apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
spec:
  selector:
    matchLabels:
      app: accountservice
  template:
    metadata:
      labels:
        app: accountservice
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/version: {{.Values.version}}
        dynatrace-release-stage: {{.Values.stage}}

    spec:
      containers:
      - name: accountservice
        image: "{{ .Values.easytrade.images.registry }}/accountservice:{{ .Values.easytrade.accountservice.tag }}"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: dt-release-info
        env:
        - name: MANAGER_HOSTANDPORT
          value: "manager:80"
        resources:
          requests:
            cpu: 150m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice
spec:
  type: ClusterIP
  selector:
    app: accountservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
