apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendreverseproxy
spec:
  selector:
    matchLabels:
      app: frontendreverseproxy
  template:
    metadata:
      labels:
        app: frontendreverseproxy
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/version: {{.Values.version}}
        dynatrace-release-stage: {{.Values.stage}}
    spec:
      containers:
      - name: frontendreverseproxy
        image: "{{ .Values.easytrade.images.registry }}/frontendreverseproxy:{{ .Values.easytrade.images.tag }}"
        envFrom:
        - configMapRef:
            name: dt-release-info
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontendreverseproxy
spec:
  type: ClusterIP
  selector:
    app: frontendreverseproxy
  ports:
    - name: http
      port: 80
      targetPort: 80
