apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/version: {{.Values.version}}
        dynatrace-release-stage: {{.Values.stage}}
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.easytrade.images.registry }}/frontend:{{ .Values.easytrade.images.tag }}"
        envFrom:
        - configMapRef:
            name: dt-release-info
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 300m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
