apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluginservice
spec:
  selector:
    matchLabels:
      app: pluginservice
  template:
    metadata:
      labels:
        app: pluginservice
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/version: {{.Values.version}}
        dynatrace-release-stage: {{.Values.stage}}
    spec:
      containers:
      - name: pluginservice
        image: "{{ .Values.easytrade.images.registry }}/pluginservice:{{ .Values.easytrade.images.tag }}"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: dt-release-info
        env:
        - name: OFFER_SERVICE__PORT
          value: '8080'
        - name: OFFER_SERVICE__DOMAIN
          value: offerservice
        - name: MANAGER__DOMAIN
          value: manager
        - name: MANAGER__PORT
          value: '80'
        resources:
          requests:
            cpu: 150m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pluginservice
spec:
  type: ClusterIP
  selector:
    app: pluginservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
